/**
 * Complete WAI-ARIA 1.2 Role Definitions
 * Comprehensive role specifications with inheritance, attributes, and constraints
 */

import { RoleDefinition, ARIARole } from '../types';

export const ARIA_ROLES: Record<ARIARole, RoleDefinition> = {
  // Abstract Roles (not for use in HTML)
  roletype: {
    name: 'roletype',
    type: 'abstract',
    abstract: true,
    superclassRoles: [],
    subclassRoles: ['structure', 'widget', 'window'],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: false,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  structure: {
    name: 'structure',
    type: 'abstract',
    abstract: true,
    superclassRoles: ['roletype'],
    subclassRoles: ['section', 'sectionhead', 'document', 'group', 'list', 'table', 'row', 'cell'],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: false,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  widget: {
    name: 'widget',
    type: 'abstract',
    abstract: true,
    superclassRoles: ['roletype'],
    subclassRoles: ['command', 'composite', 'gridcell', 'input', 'range', 'separator'],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: false,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  window: {
    name: 'window',
    type: 'abstract',
    abstract: true,
    superclassRoles: ['roletype'],
    subclassRoles: ['dialog', 'alertdialog'],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription', 'aria-modal', 'aria-expanded'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: false,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  command: {
    name: 'command',
    type: 'abstract',
    abstract: true,
    superclassRoles: ['widget'],
    subclassRoles: ['button', 'link', 'menuitem'],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: false,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  composite: {
    name: 'composite',
    type: 'abstract',
    abstract: true,
    superclassRoles: ['widget'],
    subclassRoles: ['grid', 'select', 'tablist'],
    requiredAttributes: [],
    supportedAttributes: ['aria-activedescendant', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: false,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  input: {
    name: 'input',
    type: 'abstract',
    abstract: true,
    superclassRoles: ['widget'],
    subclassRoles: ['checkbox', 'radio', 'textbox', 'searchbox', 'switch', 'slider', 'spinbutton'],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: false,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  landmark: {
    name: 'landmark',
    type: 'abstract',
    abstract: true,
    superclassRoles: ['section'],
    subclassRoles: ['banner', 'complementary', 'contentinfo', 'form', 'main', 'navigation', 'region', 'search'],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: false,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  range: {
    name: 'range',
    type: 'abstract',
    abstract: true,
    superclassRoles: ['widget'],
    subclassRoles: ['progressbar', 'scrollbar', 'slider', 'spinbutton'],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription', 'aria-valuemax', 'aria-valuemin', 'aria-valuenow', 'aria-valuetext'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: false,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  section: {
    name: 'section',
    type: 'abstract',
    abstract: true,
    superclassRoles: ['structure'],
    subclassRoles: ['alert', 'article', 'cell', 'definition', 'feed', 'figure', 'group', 'img', 'landmark', 'list', 'listitem', 'log', 'main', 'marquee', 'math', 'note', 'region', 'status', 'table', 'tabpanel', 'term', 'timer', 'toolbar', 'tooltip'],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: false,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  sectionhead: {
    name: 'sectionhead',
    type: 'abstract',
    abstract: true,
    superclassRoles: ['structure'],
    subclassRoles: ['columnheader', 'heading', 'rowheader', 'tab'],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: false,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  select: {
    name: 'select',
    type: 'abstract',
    abstract: true,
    superclassRoles: ['composite'],
    subclassRoles: ['listbox', 'menu', 'radiogroup', 'tree'],
    requiredAttributes: [],
    supportedAttributes: ['aria-activedescendant', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription', 'aria-orientation'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: false,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },

  // Concrete Widget Roles
  button: {
    name: 'button',
    type: 'widget',
    abstract: false,
    superclassRoles: ['command'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-expanded', 'aria-pressed', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: true,
  },
  checkbox: {
    name: 'checkbox',
    type: 'widget',
    abstract: false,
    superclassRoles: ['input'],
    subclassRoles: ['menuitemcheckbox', 'switch'],
    requiredAttributes: ['aria-checked'],
    supportedAttributes: ['aria-checked', 'aria-readonly', 'aria-required', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: true,
    implicitValueForRole: { 'aria-checked': 'false' },
  },
  gridcell: {
    name: 'gridcell',
    type: 'widget',
    abstract: false,
    superclassRoles: ['cell', 'widget'],
    subclassRoles: ['columnheader', 'rowheader'],
    requiredAttributes: [],
    supportedAttributes: ['aria-colindex', 'aria-colspan', 'aria-rowindex', 'aria-rowspan', 'aria-readonly', 'aria-required', 'aria-selected', 'aria-disabled', 'aria-errormessage', 'aria-expanded', 'aria-haspopup', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-dropeffect', 'aria-flowto', 'aria-grabbed', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: ['row'],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: false,
  },
  link: {
    name: 'link',
    type: 'widget',
    abstract: false,
    superclassRoles: ['command'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-expanded', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: false,
  },
  menuitem: {
    name: 'menuitem',
    type: 'widget',
    abstract: false,
    superclassRoles: ['command'],
    subclassRoles: ['menuitemcheckbox', 'menuitemradio'],
    requiredAttributes: [],
    supportedAttributes: ['aria-disabled', 'aria-expanded', 'aria-haspopup', 'aria-posinset', 'aria-setsize', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: ['menu', 'menubar'],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: false,
  },
  menuitemcheckbox: {
    name: 'menuitemcheckbox',
    type: 'widget',
    abstract: false,
    superclassRoles: ['checkbox', 'menuitem'],
    subclassRoles: [],
    requiredAttributes: ['aria-checked'],
    supportedAttributes: ['aria-checked', 'aria-readonly', 'aria-disabled', 'aria-expanded', 'aria-haspopup', 'aria-posinset', 'aria-setsize', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: ['menu', 'menubar'],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: true,
    implicitValueForRole: { 'aria-checked': 'false' },
  },
  menuitemradio: {
    name: 'menuitemradio',
    type: 'widget',
    abstract: false,
    superclassRoles: ['menuitemcheckbox', 'radio'],
    subclassRoles: [],
    requiredAttributes: ['aria-checked'],
    supportedAttributes: ['aria-checked', 'aria-readonly', 'aria-disabled', 'aria-expanded', 'aria-haspopup', 'aria-posinset', 'aria-setsize', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: ['menu', 'menubar'],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: true,
    implicitValueForRole: { 'aria-checked': 'false' },
  },
  option: {
    name: 'option',
    type: 'widget',
    abstract: false,
    superclassRoles: ['input'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-checked', 'aria-posinset', 'aria-selected', 'aria-setsize', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: ['listbox'],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: false,
    implicitValueForRole: { 'aria-selected': 'false' },
  },
  progressbar: {
    name: 'progressbar',
    type: 'widget',
    abstract: false,
    superclassRoles: ['range'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-valuemax', 'aria-valuemin', 'aria-valuenow', 'aria-valuetext', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: true,
  },
  radio: {
    name: 'radio',
    type: 'widget',
    abstract: false,
    superclassRoles: ['input'],
    subclassRoles: ['menuitemradio'],
    requiredAttributes: ['aria-checked'],
    supportedAttributes: ['aria-checked', 'aria-posinset', 'aria-setsize', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: true,
    implicitValueForRole: { 'aria-checked': 'false' },
  },
  scrollbar: {
    name: 'scrollbar',
    type: 'widget',
    abstract: false,
    superclassRoles: ['range'],
    subclassRoles: [],
    requiredAttributes: ['aria-controls', 'aria-valuenow'],
    supportedAttributes: ['aria-controls', 'aria-orientation', 'aria-valuemax', 'aria-valuemin', 'aria-valuenow', 'aria-valuetext', 'aria-atomic', 'aria-busy', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: true,
    implicitValueForRole: { 'aria-orientation': 'vertical', 'aria-valuemin': '0', 'aria-valuemax': '100' },
  },
  searchbox: {
    name: 'searchbox',
    type: 'widget',
    abstract: false,
    superclassRoles: ['textbox'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-activedescendant', 'aria-autocomplete', 'aria-multiline', 'aria-placeholder', 'aria-readonly', 'aria-required', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  separator: {
    name: 'separator',
    type: 'widget',
    abstract: false,
    superclassRoles: ['structure', 'widget'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-orientation', 'aria-valuemax', 'aria-valuemin', 'aria-valuenow', 'aria-valuetext', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: true,
    implicitValueForRole: { 'aria-orientation': 'horizontal' },
  },
  slider: {
    name: 'slider',
    type: 'widget',
    abstract: false,
    superclassRoles: ['input', 'range'],
    subclassRoles: [],
    requiredAttributes: ['aria-valuenow'],
    supportedAttributes: ['aria-errormessage', 'aria-haspopup', 'aria-invalid', 'aria-orientation', 'aria-readonly', 'aria-valuemax', 'aria-valuemin', 'aria-valuenow', 'aria-valuetext', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-flowto', 'aria-grabbed', 'aria-hidden', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: true,
    implicitValueForRole: { 'aria-orientation': 'horizontal', 'aria-valuemin': '0', 'aria-valuemax': '100' },
  },
  spinbutton: {
    name: 'spinbutton',
    type: 'widget',
    abstract: false,
    superclassRoles: ['composite', 'input', 'range'],
    subclassRoles: [],
    requiredAttributes: ['aria-valuenow'],
    supportedAttributes: ['aria-activedescendant', 'aria-errormessage', 'aria-invalid', 'aria-readonly', 'aria-required', 'aria-valuemax', 'aria-valuemin', 'aria-valuenow', 'aria-valuetext', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  switch: {
    name: 'switch',
    type: 'widget',
    abstract: false,
    superclassRoles: ['checkbox'],
    subclassRoles: [],
    requiredAttributes: ['aria-checked'],
    supportedAttributes: ['aria-checked', 'aria-readonly', 'aria-required', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: true,
    implicitValueForRole: { 'aria-checked': 'false' },
  },
  tab: {
    name: 'tab',
    type: 'widget',
    abstract: false,
    superclassRoles: ['sectionhead', 'widget'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-disabled', 'aria-expanded', 'aria-haspopup', 'aria-posinset', 'aria-selected', 'aria-setsize', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: ['tablist'],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: false,
    implicitValueForRole: { 'aria-selected': 'false' },
  },
  tabpanel: {
    name: 'tabpanel',
    type: 'widget',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  textbox: {
    name: 'textbox',
    type: 'widget',
    abstract: false,
    superclassRoles: ['input'],
    subclassRoles: ['searchbox'],
    requiredAttributes: [],
    supportedAttributes: ['aria-activedescendant', 'aria-autocomplete', 'aria-errormessage', 'aria-haspopup', 'aria-invalid', 'aria-multiline', 'aria-placeholder', 'aria-readonly', 'aria-required', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-flowto', 'aria-grabbed', 'aria-hidden', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  treeitem: {
    name: 'treeitem',
    type: 'widget',
    abstract: false,
    superclassRoles: ['listitem', 'option'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-checked', 'aria-expanded', 'aria-level', 'aria-posinset', 'aria-selected', 'aria-setsize', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: ['group', 'tree'],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: false,
  },

  // Composite Widget Roles
  combobox: {
    name: 'combobox',
    type: 'composite',
    abstract: false,
    superclassRoles: ['select'],
    subclassRoles: [],
    requiredAttributes: ['aria-controls', 'aria-expanded'],
    supportedAttributes: ['aria-activedescendant', 'aria-autocomplete', 'aria-controls', 'aria-errormessage', 'aria-expanded', 'aria-haspopup', 'aria-invalid', 'aria-readonly', 'aria-required', 'aria-atomic', 'aria-busy', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-flowto', 'aria-grabbed', 'aria-hidden', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-orientation', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
    implicitValueForRole: { 'aria-haspopup': 'listbox' },
  },
  grid: {
    name: 'grid',
    type: 'composite',
    abstract: false,
    superclassRoles: ['composite', 'table'],
    subclassRoles: ['treegrid'],
    requiredAttributes: [],
    supportedAttributes: ['aria-activedescendant', 'aria-colcount', 'aria-level', 'aria-multiselectable', 'aria-readonly', 'aria-rowcount', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: ['row', 'rowgroup'],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  listbox: {
    name: 'listbox',
    type: 'composite',
    abstract: false,
    superclassRoles: ['select'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-activedescendant', 'aria-errormessage', 'aria-expanded', 'aria-invalid', 'aria-multiselectable', 'aria-readonly', 'aria-required', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-orientation', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: ['option'],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  menu: {
    name: 'menu',
    type: 'composite',
    abstract: false,
    superclassRoles: ['select'],
    subclassRoles: ['menubar'],
    requiredAttributes: [],
    supportedAttributes: ['aria-activedescendant', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-orientation', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: ['menuitem', 'menuitemcheckbox', 'menuitemradio'],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
    implicitValueForRole: { 'aria-orientation': 'vertical' },
  },
  menubar: {
    name: 'menubar',
    type: 'composite',
    abstract: false,
    superclassRoles: ['menu'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-activedescendant', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-orientation', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: ['menuitem', 'menuitemcheckbox', 'menuitemradio'],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
    implicitValueForRole: { 'aria-orientation': 'horizontal' },
  },
  radiogroup: {
    name: 'radiogroup',
    type: 'composite',
    abstract: false,
    superclassRoles: ['select'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-activedescendant', 'aria-errormessage', 'aria-invalid', 'aria-readonly', 'aria-required', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-orientation', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: ['radio'],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  tablist: {
    name: 'tablist',
    type: 'composite',
    abstract: false,
    superclassRoles: ['composite'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-activedescendant', 'aria-level', 'aria-multiselectable', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-orientation', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: ['tab'],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
    implicitValueForRole: { 'aria-orientation': 'horizontal' },
  },
  tree: {
    name: 'tree',
    type: 'composite',
    abstract: false,
    superclassRoles: ['select'],
    subclassRoles: ['treegrid'],
    requiredAttributes: [],
    supportedAttributes: ['aria-activedescendant', 'aria-errormessage', 'aria-invalid', 'aria-multiselectable', 'aria-required', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-orientation', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: ['treeitem'],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  treegrid: {
    name: 'treegrid',
    type: 'composite',
    abstract: false,
    superclassRoles: ['grid', 'tree'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-activedescendant', 'aria-colcount', 'aria-errormessage', 'aria-invalid', 'aria-level', 'aria-multiselectable', 'aria-readonly', 'aria-required', 'aria-rowcount', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-orientation', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: ['row'],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },

  // Document Structure Roles
  article: {
    name: 'article',
    type: 'document',
    abstract: false,
    superclassRoles: ['document'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-posinset', 'aria-setsize', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  cell: {
    name: 'cell',
    type: 'document',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: ['columnheader', 'gridcell', 'rowheader'],
    requiredAttributes: [],
    supportedAttributes: ['aria-colindex', 'aria-colspan', 'aria-rowindex', 'aria-rowspan', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: ['row'],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: false,
  },
  columnheader: {
    name: 'columnheader',
    type: 'document',
    abstract: false,
    superclassRoles: ['cell', 'gridcell', 'sectionhead'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-colindex', 'aria-colspan', 'aria-disabled', 'aria-errormessage', 'aria-expanded', 'aria-haspopup', 'aria-invalid', 'aria-readonly', 'aria-required', 'aria-rowindex', 'aria-rowspan', 'aria-selected', 'aria-sort', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-dropeffect', 'aria-flowto', 'aria-grabbed', 'aria-hidden', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: ['row'],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: false,
  },
  definition: {
    name: 'definition',
    type: 'document',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  directory: {
    name: 'directory',
    type: 'document',
    abstract: false,
    superclassRoles: ['list'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  document: {
    name: 'document',
    type: 'document',
    abstract: false,
    superclassRoles: ['structure'],
    subclassRoles: ['article'],
    requiredAttributes: [],
    supportedAttributes: ['aria-expanded', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  feed: {
    name: 'feed',
    type: 'document',
    abstract: false,
    superclassRoles: ['list'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: ['article'],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  figure: {
    name: 'figure',
    type: 'document',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  group: {
    name: 'group',
    type: 'document',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: ['row', 'select', 'toolbar'],
    requiredAttributes: [],
    supportedAttributes: ['aria-activedescendant', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  heading: {
    name: 'heading',
    type: 'document',
    abstract: false,
    superclassRoles: ['sectionhead'],
    subclassRoles: [],
    requiredAttributes: ['aria-level'],
    supportedAttributes: ['aria-level', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: false,
  },
  img: {
    name: 'img',
    type: 'document',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: true,
  },
  list: {
    name: 'list',
    type: 'document',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: ['directory', 'feed'],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: ['listitem'],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  listitem: {
    name: 'listitem',
    type: 'document',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: ['treeitem'],
    requiredAttributes: [],
    supportedAttributes: ['aria-level', 'aria-posinset', 'aria-setsize', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: ['directory', 'list'],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: false,
  },
  math: {
    name: 'math',
    type: 'document',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: true,
  },
  none: {
    name: 'none',
    type: 'document',
    abstract: false,
    superclassRoles: ['structure'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: [],
    prohibitedAttributes: ['aria-label', 'aria-labelledby'],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: false,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  note: {
    name: 'note',
    type: 'document',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  presentation: {
    name: 'presentation',
    type: 'document',
    abstract: false,
    superclassRoles: ['structure'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: [],
    prohibitedAttributes: ['aria-label', 'aria-labelledby'],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: false,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  row: {
    name: 'row',
    type: 'document',
    abstract: false,
    superclassRoles: ['group', 'sectionhead', 'widget'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-colindex', 'aria-expanded', 'aria-level', 'aria-posinset', 'aria-rowindex', 'aria-selected', 'aria-setsize', 'aria-activedescendant', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: ['cell', 'columnheader', 'gridcell', 'rowheader'],
    requiredContextRole: ['grid', 'rowgroup', 'table', 'treegrid'],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: false,
  },
  rowgroup: {
    name: 'rowgroup',
    type: 'document',
    abstract: false,
    superclassRoles: ['structure'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: ['row'],
    requiredContextRole: ['grid', 'table', 'treegrid'],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  rowheader: {
    name: 'rowheader',
    type: 'document',
    abstract: false,
    superclassRoles: ['cell', 'gridcell', 'sectionhead'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-colindex', 'aria-colspan', 'aria-disabled', 'aria-errormessage', 'aria-expanded', 'aria-haspopup', 'aria-invalid', 'aria-readonly', 'aria-required', 'aria-rowindex', 'aria-rowspan', 'aria-selected', 'aria-sort', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-dropeffect', 'aria-flowto', 'aria-grabbed', 'aria-hidden', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: ['row'],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: false,
  },
  table: {
    name: 'table',
    type: 'document',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: ['grid'],
    requiredAttributes: [],
    supportedAttributes: ['aria-colcount', 'aria-rowcount', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: ['row', 'rowgroup'],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  term: {
    name: 'term',
    type: 'document',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  toolbar: {
    name: 'toolbar',
    type: 'document',
    abstract: false,
    superclassRoles: ['group'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-activedescendant', 'aria-orientation', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
    implicitValueForRole: { 'aria-orientation': 'horizontal' },
  },
  tooltip: {
    name: 'tooltip',
    type: 'document',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: true,
    childrenPresentational: false,
  },

  // Landmark Roles
  banner: {
    name: 'banner',
    type: 'landmark',
    abstract: false,
    superclassRoles: ['landmark'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  complementary: {
    name: 'complementary',
    type: 'landmark',
    abstract: false,
    superclassRoles: ['landmark'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  contentinfo: {
    name: 'contentinfo',
    type: 'landmark',
    abstract: false,
    superclassRoles: ['landmark'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  form: {
    name: 'form',
    type: 'landmark',
    abstract: false,
    superclassRoles: ['landmark'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  main: {
    name: 'main',
    type: 'landmark',
    abstract: false,
    superclassRoles: ['landmark'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  navigation: {
    name: 'navigation',
    type: 'landmark',
    abstract: false,
    superclassRoles: ['landmark'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  region: {
    name: 'region',
    type: 'landmark',
    abstract: false,
    superclassRoles: ['landmark'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  search: {
    name: 'search',
    type: 'landmark',
    abstract: false,
    superclassRoles: ['landmark'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },

  // Live Region Roles
  alert: {
    name: 'alert',
    type: 'live',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: ['alertdialog'],
    requiredAttributes: [],
    supportedAttributes: ['aria-expanded', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
    implicitValueForRole: { 'aria-live': 'assertive', 'aria-atomic': 'true' },
  },
  log: {
    name: 'log',
    type: 'live',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
    implicitValueForRole: { 'aria-live': 'polite' },
  },
  marquee: {
    name: 'marquee',
    type: 'live',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
    implicitValueForRole: { 'aria-live': 'off' },
  },
  status: {
    name: 'status',
    type: 'live',
    abstract: false,
    superclassRoles: ['section'],
    subclassRoles: ['timer'],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
    implicitValueForRole: { 'aria-live': 'polite', 'aria-atomic': 'true' },
  },
  timer: {
    name: 'timer',
    type: 'live',
    abstract: false,
    superclassRoles: ['status'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: false,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },

  // Window Roles
  alertdialog: {
    name: 'alertdialog',
    type: 'window',
    abstract: false,
    superclassRoles: ['alert', 'dialog'],
    subclassRoles: [],
    requiredAttributes: [],
    supportedAttributes: ['aria-expanded', 'aria-modal', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
  dialog: {
    name: 'dialog',
    type: 'window',
    abstract: false,
    superclassRoles: ['window'],
    subclassRoles: ['alertdialog'],
    requiredAttributes: [],
    supportedAttributes: ['aria-expanded', 'aria-modal', 'aria-atomic', 'aria-busy', 'aria-controls', 'aria-current', 'aria-describedby', 'aria-details', 'aria-disabled', 'aria-dropeffect', 'aria-errormessage', 'aria-flowto', 'aria-grabbed', 'aria-haspopup', 'aria-hidden', 'aria-invalid', 'aria-keyshortcuts', 'aria-label', 'aria-labelledby', 'aria-live', 'aria-owns', 'aria-relevant', 'aria-roledescription'],
    prohibitedAttributes: [],
    requiredOwnedElements: [],
    requiredContextRole: [],
    accessibleNameRequired: true,
    accessibleNameFromAuthor: true,
    accessibleNameFromContent: false,
    childrenPresentational: false,
  },
};

export function getRoleDefinition(role: ARIARole): RoleDefinition | null {
  return ARIA_ROLES[role] || null;
}

export function isAbstractRole(role: ARIARole): boolean {
  const definition = getRoleDefinition(role);
  return definition?.abstract || false;
}

export function isValidRole(role: string): role is ARIARole {
  return role in ARIA_ROLES;
}
