import { ReportTemplate } from '../types';

/**
 * Compliance Audit Template
 * Formal compliance assessment for regulatory and legal requirements
 */
export const ComplianceAuditTemplate: ReportTemplate = {
  id: 'compliance-audit',
  name: 'Compliance Audit Report',
  description:
    'Formal accessibility compliance audit report for regulatory requirements, legal documentation, and certification purposes.',
  type: 'compliance',
  sections: [
    {
      id: 'audit-overview',
      title: 'Audit Overview',
      type: 'summary',
      order: 0,
      enabled: true,
      subsections: [
        {
          id: 'audit-scope',
          title: 'Audit Scope & Objectives',
          type: 'custom',
          order: 0,
          enabled: true,
        },
        {
          id: 'audit-methodology',
          title: 'Audit Methodology',
          type: 'custom',
          order: 1,
          enabled: true,
        },
        {
          id: 'audit-team',
          title: 'Audit Team & Credentials',
          type: 'custom',
          order: 2,
          enabled: true,
        },
      ],
    },
    {
      id: 'compliance-statement',
      title: 'Compliance Statement',
      type: 'summary',
      order: 1,
      enabled: true,
      subsections: [
        {
          id: 'wcag-compliance-status',
          title: 'WCAG 2.1 Compliance Status',
          type: 'metrics',
          order: 0,
          enabled: true,
        },
        {
          id: 'section-508-status',
          title: 'Section 508 Compliance Status',
          type: 'metrics',
          order: 1,
          enabled: true,
        },
        {
          id: 'ada-status',
          title: 'ADA Compliance Status',
          type: 'metrics',
          order: 2,
          enabled: true,
        },
        {
          id: 'en-301-549-status',
          title: 'EN 301 549 Compliance Status',
          type: 'metrics',
          order: 3,
          enabled: true,
        },
      ],
    },
    {
      id: 'success-criteria-assessment',
      title: 'Success Criteria Assessment',
      type: 'metrics',
      order: 2,
      enabled: true,
      subsections: [
        {
          id: 'level-a-criteria',
          title: 'Level A Success Criteria',
          type: 'metrics',
          order: 0,
          enabled: true,
        },
        {
          id: 'level-aa-criteria',
          title: 'Level AA Success Criteria',
          type: 'metrics',
          order: 1,
          enabled: true,
        },
        {
          id: 'level-aaa-criteria',
          title: 'Level AAA Success Criteria',
          type: 'metrics',
          order: 2,
          enabled: true,
        },
      ],
    },
    {
      id: 'non-compliance-findings',
      title: 'Non-Compliance Findings',
      type: 'issues',
      order: 3,
      enabled: true,
      subsections: [
        {
          id: 'critical-violations',
          title: 'Critical Violations',
          type: 'issues',
          order: 0,
          enabled: true,
        },
        {
          id: 'serious-violations',
          title: 'Serious Violations',
          type: 'issues',
          order: 1,
          enabled: true,
        },
        {
          id: 'moderate-violations',
          title: 'Moderate Violations',
          type: 'issues',
          order: 2,
          enabled: true,
        },
      ],
    },
    {
      id: 'risk-assessment',
      title: 'Risk Assessment',
      type: 'custom',
      order: 4,
      enabled: true,
      subsections: [
        {
          id: 'legal-risks',
          title: 'Legal & Regulatory Risks',
          type: 'custom',
          order: 0,
          enabled: true,
        },
        {
          id: 'business-risks',
          title: 'Business Impact Risks',
          type: 'custom',
          order: 1,
          enabled: true,
        },
        {
          id: 'reputational-risks',
          title: 'Reputational Risks',
          type: 'custom',
          order: 2,
          enabled: true,
        },
      ],
    },
    {
      id: 'compliance-roadmap',
      title: 'Compliance Roadmap',
      type: 'recommendations',
      order: 5,
      enabled: true,
      subsections: [
        {
          id: 'immediate-actions',
          title: 'Immediate Actions (0-30 days)',
          type: 'recommendations',
          order: 0,
          enabled: true,
        },
        {
          id: 'short-term-actions',
          title: 'Short-term Actions (1-3 months)',
          type: 'recommendations',
          order: 1,
          enabled: true,
        },
        {
          id: 'long-term-actions',
          title: 'Long-term Actions (3-12 months)',
          type: 'recommendations',
          order: 2,
          enabled: true,
        },
      ],
    },
    {
      id: 'attestation',
      title: 'Attestation & Certification',
      type: 'custom',
      order: 6,
      enabled: true,
    },
    {
      id: 'audit-appendix',
      title: 'Audit Appendix',
      type: 'custom',
      order: 7,
      enabled: true,
      subsections: [
        {
          id: 'testing-evidence',
          title: 'Testing Evidence',
          type: 'custom',
          order: 0,
          enabled: true,
        },
        {
          id: 'regulatory-references',
          title: 'Regulatory References',
          type: 'custom',
          order: 1,
          enabled: true,
        },
        {
          id: 'vpat-summary',
          title: 'VPAT Summary',
          type: 'custom',
          order: 2,
          enabled: true,
        },
      ],
    },
  ],
  defaultBranding: {
    companyName: 'Compliance Audit',
    primaryColor: '#2e7d32',
    secondaryColor: '#424242',
    accentColor: '#ff6f00',
    fontFamily: 'Times New Roman, serif',
    includePageNumbers: true,
    includeDateGenerated: true,
    footerText: 'Confidential Compliance Audit Report',
  },
};
