import { ReportTemplate } from '../types';

/**
 * Remediation Guide Template
 * Action-oriented guide for fixing accessibility issues
 */
export const RemediationGuideTemplate: ReportTemplate = {
  id: 'remediation-guide',
  name: 'Accessibility Remediation Guide',
  description:
    'Step-by-step remediation guide with actionable fixes, code examples, and implementation timelines. Perfect for development sprints.',
  type: 'remediation',
  sections: [
    {
      id: 'remediation-overview',
      title: 'Remediation Overview',
      type: 'summary',
      order: 0,
      enabled: true,
      subsections: [
        {
          id: 'current-state',
          title: 'Current Accessibility State',
          type: 'summary',
          order: 0,
          enabled: true,
        },
        {
          id: 'target-state',
          title: 'Target Accessibility Goals',
          type: 'summary',
          order: 1,
          enabled: true,
        },
        {
          id: 'effort-estimate',
          title: 'Overall Effort Estimate',
          type: 'summary',
          order: 2,
          enabled: true,
        },
      ],
    },
    {
      id: 'priority-matrix',
      title: 'Issue Priority Matrix',
      type: 'custom',
      order: 1,
      enabled: true,
      subsections: [
        {
          id: 'high-priority-high-impact',
          title: 'High Priority, High Impact',
          type: 'issues',
          order: 0,
          enabled: true,
        },
        {
          id: 'high-priority-low-effort',
          title: 'High Priority, Low Effort (Quick Wins)',
          type: 'issues',
          order: 1,
          enabled: true,
        },
        {
          id: 'medium-priority',
          title: 'Medium Priority Issues',
          type: 'issues',
          order: 2,
          enabled: true,
        },
      ],
    },
    {
      id: 'sprint-planning',
      title: 'Sprint Planning Guide',
      type: 'recommendations',
      order: 2,
      enabled: true,
      subsections: [
        {
          id: 'sprint-1',
          title: 'Sprint 1: Critical Fixes',
          type: 'recommendations',
          order: 0,
          enabled: true,
        },
        {
          id: 'sprint-2',
          title: 'Sprint 2: Serious Issues',
          type: 'recommendations',
          order: 1,
          enabled: true,
        },
        {
          id: 'sprint-3',
          title: 'Sprint 3: Moderate Issues',
          type: 'recommendations',
          order: 2,
          enabled: true,
        },
        {
          id: 'sprint-4',
          title: 'Sprint 4: Minor Issues & Polish',
          type: 'recommendations',
          order: 3,
          enabled: true,
        },
      ],
    },
    {
      id: 'remediation-steps',
      title: 'Detailed Remediation Steps',
      type: 'recommendations',
      order: 3,
      enabled: true,
      subsections: [
        {
          id: 'keyboard-navigation',
          title: 'Keyboard Navigation Fixes',
          type: 'recommendations',
          order: 0,
          enabled: true,
        },
        {
          id: 'screen-reader',
          title: 'Screen Reader Compatibility',
          type: 'recommendations',
          order: 1,
          enabled: true,
        },
        {
          id: 'color-contrast',
          title: 'Color Contrast Improvements',
          type: 'recommendations',
          order: 2,
          enabled: true,
        },
        {
          id: 'form-labels',
          title: 'Form Labels & Instructions',
          type: 'recommendations',
          order: 3,
          enabled: true,
        },
        {
          id: 'heading-structure',
          title: 'Heading Structure & Landmarks',
          type: 'recommendations',
          order: 4,
          enabled: true,
        },
        {
          id: 'alternative-text',
          title: 'Alternative Text for Images',
          type: 'recommendations',
          order: 5,
          enabled: true,
        },
      ],
    },
    {
      id: 'code-solutions',
      title: 'Code Solutions & Examples',
      type: 'technical',
      order: 4,
      enabled: true,
      subsections: [
        {
          id: 'before-after-examples',
          title: 'Before/After Code Examples',
          type: 'technical',
          order: 0,
          enabled: true,
        },
        {
          id: 'component-patterns',
          title: 'Accessible Component Patterns',
          type: 'technical',
          order: 1,
          enabled: true,
        },
        {
          id: 'aria-patterns',
          title: 'ARIA Implementation Patterns',
          type: 'technical',
          order: 2,
          enabled: true,
        },
      ],
    },
    {
      id: 'testing-validation',
      title: 'Testing & Validation',
      type: 'technical',
      order: 5,
      enabled: true,
      subsections: [
        {
          id: 'automated-testing-setup',
          title: 'Automated Testing Setup',
          type: 'technical',
          order: 0,
          enabled: true,
        },
        {
          id: 'manual-testing-procedures',
          title: 'Manual Testing Procedures',
          type: 'technical',
          order: 1,
          enabled: true,
        },
        {
          id: 'regression-testing',
          title: 'Regression Testing Plan',
          type: 'technical',
          order: 2,
          enabled: true,
        },
      ],
    },
    {
      id: 'implementation-timeline',
      title: 'Implementation Timeline',
      type: 'custom',
      order: 6,
      enabled: true,
      subsections: [
        {
          id: 'week-by-week',
          title: 'Week-by-Week Breakdown',
          type: 'custom',
          order: 0,
          enabled: true,
        },
        {
          id: 'milestones',
          title: 'Key Milestones',
          type: 'custom',
          order: 1,
          enabled: true,
        },
        {
          id: 'dependencies',
          title: 'Dependencies & Blockers',
          type: 'custom',
          order: 2,
          enabled: true,
        },
      ],
    },
    {
      id: 'resources',
      title: 'Resources & References',
      type: 'custom',
      order: 7,
      enabled: true,
      subsections: [
        {
          id: 'wcag-guidelines',
          title: 'WCAG Guidelines & Techniques',
          type: 'custom',
          order: 0,
          enabled: true,
        },
        {
          id: 'tools-libraries',
          title: 'Recommended Tools & Libraries',
          type: 'custom',
          order: 1,
          enabled: true,
        },
        {
          id: 'training-materials',
          title: 'Training Materials',
          type: 'custom',
          order: 2,
          enabled: true,
        },
      ],
    },
  ],
  defaultBranding: {
    companyName: 'Remediation Team',
    primaryColor: '#9c27b0',
    secondaryColor: '#424242',
    accentColor: '#00bcd4',
    fontFamily: 'Arial, sans-serif',
    includePageNumbers: true,
    includeDateGenerated: true,
  },
};
